please review module 5
js-tasks-ru/jsbasic-20230209_mariana0 pull request #5
Opened 2023-03-02 17:57 UTC by MarianaSalmassi

2023-03-02 17:58 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-03-04 12:49 UTC, koalex requested changes
Исправить замечание **5-2**

2023-03-04 12:49 UTC, koalex commented on 5-module/2-task/index.js
> +  const content = document.querySelector(".text");
Здесь надо искать по` id`, вот так: `document.querySelector("#text");`

2023-03-04 12:49 UTC, koalex commented on 5-module/2-task/index.js
> +    content.classList.toggle("hidden");
И надо не класс проставлять, а атрибут `hidden`.
Внимательнее пожалуйста)) [Задание](https://learn.javascript.ru/taskbook/jsbasic-20230209/workspace/5-module/2-task#)

2023-03-04 16:01 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-03-05 05:44 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-03-05 05:49 UTC, koalex requested changes
5-2

2023-03-05 05:49 UTC, koalex commented on 5-module/2-task/index.js
> +      text.classList.toggle('hidden');
В прошлом комментарии я говорил, что надо менять атрибут `hidden`, а не **css**-класс, вот так:
`text.hidden = !text.hidden;`

2023-03-05 05:59 UTC, jsru commented
Добавляю преподавателя (@koalex) для код-ревью.

2023-03-05 06:00 UTC, koalex approved these changes

2023-03-05 06:01 UTC, merged